/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.0.4
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.os.api.model;

import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets AcknowledgementType
 */
@JsonAdapter(AcknowledgementType.Adapter.class)
public enum AcknowledgementType {
  @SerializedName("POSITIVE")
  POSITIVE("POSITIVE"),
  @SerializedName("NEGATIVE")
  NEGATIVE("NEGATIVE");

  private String value;

  AcknowledgementType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AcknowledgementType fromValue(String input) {
    for (AcknowledgementType b : AcknowledgementType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<AcknowledgementType> {
    @Override
    public void write(final JsonWriter jsonWriter, final AcknowledgementType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public AcknowledgementType read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return AcknowledgementType.fromValue((String)(value));
    }
  }
}
