/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.0.3
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.os.api.model;

import java.time.OffsetDateTime;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Rerate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-24T20:38:16.660246147Z[GMT]")

public class Rerate {
  @SerializedName("rerateId")
  private String rerateId = null;

  @SerializedName("contractId")
  private String contractId = null;

  @SerializedName("status")
  private ContractStatus status = null;

  @SerializedName("rate")
  private OneOfRerateRate rate = null;

  @SerializedName("rerate")
  private OneOfRerateRerate rerate = null;

  @SerializedName("lastUpdateDatetime")
  private OffsetDateTime lastUpdateDatetime = null;

  public Rerate rerateId(String rerateId) {
    this.rerateId = rerateId;
    return this;
  }

   /**
   * Get rerateId
   * @return rerateId
  **/
  @Schema(required = true, description = "")
  public String getRerateId() {
    return rerateId;
  }

  public void setRerateId(String rerateId) {
    this.rerateId = rerateId;
  }

  public Rerate contractId(String contractId) {
    this.contractId = contractId;
    return this;
  }

   /**
   * Get contractId
   * @return contractId
  **/
  @Schema(required = true, description = "")
  public String getContractId() {
    return contractId;
  }

  public void setContractId(String contractId) {
    this.contractId = contractId;
  }

  public Rerate status(ContractStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public ContractStatus getStatus() {
    return status;
  }

  public void setStatus(ContractStatus status) {
    this.status = status;
  }

  public Rerate rate(OneOfRerateRate rate) {
    this.rate = rate;
    return this;
  }

   /**
   * Get rate
   * @return rate
  **/
  @Schema(required = true, description = "")
  public OneOfRerateRate getRate() {
    return rate;
  }

  public void setRate(OneOfRerateRate rate) {
    this.rate = rate;
  }

  public Rerate rerate(OneOfRerateRerate rerate) {
    this.rerate = rerate;
    return this;
  }

   /**
   * Get rerate
   * @return rerate
  **/
  @Schema(required = true, description = "")
  public OneOfRerateRerate getRerate() {
    return rerate;
  }

  public void setRerate(OneOfRerateRerate rerate) {
    this.rerate = rerate;
  }

  public Rerate lastUpdateDatetime(OffsetDateTime lastUpdateDatetime) {
    this.lastUpdateDatetime = lastUpdateDatetime;
    return this;
  }

   /**
   * Get lastUpdateDatetime
   * @return lastUpdateDatetime
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getLastUpdateDatetime() {
    return lastUpdateDatetime;
  }

  public void setLastUpdateDatetime(OffsetDateTime lastUpdateDatetime) {
    this.lastUpdateDatetime = lastUpdateDatetime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rerate rerate = (Rerate) o;
    return Objects.equals(this.rerateId, rerate.rerateId) &&
        Objects.equals(this.contractId, rerate.contractId) &&
        Objects.equals(this.status, rerate.status) &&
        Objects.equals(this.rate, rerate.rate) &&
        Objects.equals(this.rerate, rerate.rerate) &&
        Objects.equals(this.lastUpdateDatetime, rerate.lastUpdateDatetime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rerateId, contractId, status, rate, rerate, lastUpdateDatetime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rerate {\n");
    
    sb.append("    rerateId: ").append(toIndentedString(rerateId)).append("\n");
    sb.append("    contractId: ").append(toIndentedString(contractId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    rerate: ").append(toIndentedString(rerate)).append("\n");
    sb.append("    lastUpdateDatetime: ").append(toIndentedString(lastUpdateDatetime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
