/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.0.3
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.os.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * Venue
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-09-07T19:46:14.871947520Z[GMT]")

public class Venue {
  @SerializedName("type")
  private VenueType type = null;

  @SerializedName("platform")
  private Platform platform = null;

  @SerializedName("venueParties")
  private VenueParties venueParties = null;

  @SerializedName("localVenueFields")
  private List<LocalVenueField> localVenueFields = null;

  public Venue type(VenueType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public VenueType getType() {
    return type;
  }

  public void setType(VenueType type) {
    this.type = type;
  }

  public Venue platform(Platform platform) {
    this.platform = platform;
    return this;
  }

   /**
   * Get platform
   * @return platform
  **/
  @Schema(description = "")
  public Platform getPlatform() {
    return platform;
  }

  public void setPlatform(Platform platform) {
    this.platform = platform;
  }

  public Venue venueParties(VenueParties venueParties) {
    this.venueParties = venueParties;
    return this;
  }

   /**
   * Get venueParties
   * @return venueParties
  **/
  @Schema(description = "")
  public VenueParties getVenueParties() {
    return venueParties;
  }

  public void setVenueParties(VenueParties venueParties) {
    this.venueParties = venueParties;
  }

  public Venue localVenueFields(List<LocalVenueField> localVenueFields) {
    this.localVenueFields = localVenueFields;
    return this;
  }

  public Venue addLocalVenueFieldsItem(LocalVenueField localVenueFieldsItem) {
    if (this.localVenueFields == null) {
      this.localVenueFields = new ArrayList<LocalVenueField>();
    }
    this.localVenueFields.add(localVenueFieldsItem);
    return this;
  }

   /**
   * Get localVenueFields
   * @return localVenueFields
  **/
  @Schema(description = "")
  public List<LocalVenueField> getLocalVenueFields() {
    return localVenueFields;
  }

  public void setLocalVenueFields(List<LocalVenueField> localVenueFields) {
    this.localVenueFields = localVenueFields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Venue venue = (Venue) o;
    return Objects.equals(this.type, venue.type) &&
        Objects.equals(this.platform, venue.platform) &&
        Objects.equals(this.venueParties, venue.venueParties) &&
        Objects.equals(this.localVenueFields, venue.localVenueFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, platform, venueParties, localVenueFields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Venue {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    venueParties: ").append(toIndentedString(venueParties)).append("\n");
    sb.append("    localVenueFields: ").append(toIndentedString(localVenueFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
