/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.0.4
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * BuyinInitiate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-19T17:47:23.155955443Z[GMT]")

public class BuyinInitiate {
  @SerializedName("buyinIniitiateId")
  private String buyinIniitiateId = null;

  @SerializedName("contractId")
  private String contractId = null;

  @SerializedName("status")
  private BuyinInitiateStatus status = null;

  @SerializedName("openQuantity")
  private BigDecimal openQuantity = null;

  @SerializedName("quantity")
  private BigDecimal quantity = null;

  @SerializedName("lastUpdateDatetime")
  private OffsetDateTime lastUpdateDatetime = null;

  public BuyinInitiate buyinIniitiateId(String buyinIniitiateId) {
    this.buyinIniitiateId = buyinIniitiateId;
    return this;
  }

   /**
   * Get buyinIniitiateId
   * @return buyinIniitiateId
  **/
  @Schema(description = "")
  public String getBuyinIniitiateId() {
    return buyinIniitiateId;
  }

  public void setBuyinIniitiateId(String buyinIniitiateId) {
    this.buyinIniitiateId = buyinIniitiateId;
  }

  public BuyinInitiate contractId(String contractId) {
    this.contractId = contractId;
    return this;
  }

   /**
   * Get contractId
   * @return contractId
  **/
  @Schema(required = true, description = "")
  public String getContractId() {
    return contractId;
  }

  public void setContractId(String contractId) {
    this.contractId = contractId;
  }

  public BuyinInitiate status(BuyinInitiateStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public BuyinInitiateStatus getStatus() {
    return status;
  }

  public void setStatus(BuyinInitiateStatus status) {
    this.status = status;
  }

  public BuyinInitiate openQuantity(BigDecimal openQuantity) {
    this.openQuantity = openQuantity;
    return this;
  }

   /**
   * Get openQuantity
   * @return openQuantity
  **/
  @Schema(required = true, description = "")
  public BigDecimal getOpenQuantity() {
    return openQuantity;
  }

  public void setOpenQuantity(BigDecimal openQuantity) {
    this.openQuantity = openQuantity;
  }

  public BuyinInitiate quantity(BigDecimal quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @Schema(description = "")
  public BigDecimal getQuantity() {
    return quantity;
  }

  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }

  public BuyinInitiate lastUpdateDatetime(OffsetDateTime lastUpdateDatetime) {
    this.lastUpdateDatetime = lastUpdateDatetime;
    return this;
  }

   /**
   * Get lastUpdateDatetime
   * @return lastUpdateDatetime
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getLastUpdateDatetime() {
    return lastUpdateDatetime;
  }

  public void setLastUpdateDatetime(OffsetDateTime lastUpdateDatetime) {
    this.lastUpdateDatetime = lastUpdateDatetime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuyinInitiate buyinInitiate = (BuyinInitiate) o;
    return Objects.equals(this.buyinIniitiateId, buyinInitiate.buyinIniitiateId) &&
        Objects.equals(this.contractId, buyinInitiate.contractId) &&
        Objects.equals(this.status, buyinInitiate.status) &&
        Objects.equals(this.openQuantity, buyinInitiate.openQuantity) &&
        Objects.equals(this.quantity, buyinInitiate.quantity) &&
        Objects.equals(this.lastUpdateDatetime, buyinInitiate.lastUpdateDatetime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buyinIniitiateId, contractId, status, openQuantity, quantity, lastUpdateDatetime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuyinInitiate {\n");
    
    sb.append("    buyinIniitiateId: ").append(toIndentedString(buyinIniitiateId)).append("\n");
    sb.append("    contractId: ").append(toIndentedString(contractId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    openQuantity: ").append(toIndentedString(openQuantity)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    lastUpdateDatetime: ").append(toIndentedString(lastUpdateDatetime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
