/*
 * 1Source Ledger API
 * 1Source Ledger API provides client access to the 1Source Ledger. You can find out more about 1Source at [https://equilend.com](https://equilend.com).  This specification is work in progress. The design is meant to model the securities lending life cycle in as clean a way as possible while being robust enough to easily translate to ISLA CDM workflows and data model.  API specification is the intellectual property of EquiLend LLC and should not be copied or disseminated in any way. 
 *
 * OpenAPI spec version: 1.0.4
 * Contact: 1source_help@equilend.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ContractSplit
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-03-19T17:47:23.155955443Z[GMT]")

public class ContractSplit {
  @SerializedName("contractSplitId")
  private String contractSplitId = null;

  @SerializedName("contractSplitStatus")
  private ContractSplitStatus contractSplitStatus = null;

  @SerializedName("splitLots")
  private List<ContractSplitLot> splitLots = null;

  @SerializedName("lastUpdateDatetime")
  private OffsetDateTime lastUpdateDatetime = null;

  public ContractSplit contractSplitId(String contractSplitId) {
    this.contractSplitId = contractSplitId;
    return this;
  }

   /**
   * Get contractSplitId
   * @return contractSplitId
  **/
  @Schema(required = true, description = "")
  public String getContractSplitId() {
    return contractSplitId;
  }

  public void setContractSplitId(String contractSplitId) {
    this.contractSplitId = contractSplitId;
  }

  public ContractSplit contractSplitStatus(ContractSplitStatus contractSplitStatus) {
    this.contractSplitStatus = contractSplitStatus;
    return this;
  }

   /**
   * Get contractSplitStatus
   * @return contractSplitStatus
  **/
  @Schema(required = true, description = "")
  public ContractSplitStatus getContractSplitStatus() {
    return contractSplitStatus;
  }

  public void setContractSplitStatus(ContractSplitStatus contractSplitStatus) {
    this.contractSplitStatus = contractSplitStatus;
  }

  public ContractSplit splitLots(List<ContractSplitLot> splitLots) {
    this.splitLots = splitLots;
    return this;
  }

  public ContractSplit addSplitLotsItem(ContractSplitLot splitLotsItem) {
    if (this.splitLots == null) {
      this.splitLots = new ArrayList<ContractSplitLot>();
    }
    this.splitLots.add(splitLotsItem);
    return this;
  }

   /**
   * Get splitLots
   * @return splitLots
  **/
  @Schema(description = "")
  public List<ContractSplitLot> getSplitLots() {
    return splitLots;
  }

  public void setSplitLots(List<ContractSplitLot> splitLots) {
    this.splitLots = splitLots;
  }

  public ContractSplit lastUpdateDatetime(OffsetDateTime lastUpdateDatetime) {
    this.lastUpdateDatetime = lastUpdateDatetime;
    return this;
  }

   /**
   * Get lastUpdateDatetime
   * @return lastUpdateDatetime
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getLastUpdateDatetime() {
    return lastUpdateDatetime;
  }

  public void setLastUpdateDatetime(OffsetDateTime lastUpdateDatetime) {
    this.lastUpdateDatetime = lastUpdateDatetime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContractSplit contractSplit = (ContractSplit) o;
    return Objects.equals(this.contractSplitId, contractSplit.contractSplitId) &&
        Objects.equals(this.contractSplitStatus, contractSplit.contractSplitStatus) &&
        Objects.equals(this.splitLots, contractSplit.splitLots) &&
        Objects.equals(this.lastUpdateDatetime, contractSplit.lastUpdateDatetime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractSplitId, contractSplitStatus, splitLots, lastUpdateDatetime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContractSplit {\n");
    
    sb.append("    contractSplitId: ").append(toIndentedString(contractSplitId)).append("\n");
    sb.append("    contractSplitStatus: ").append(toIndentedString(contractSplitStatus)).append("\n");
    sb.append("    splitLots: ").append(toIndentedString(splitLots)).append("\n");
    sb.append("    lastUpdateDatetime: ").append(toIndentedString(lastUpdateDatetime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
